# Generated by Django 5.2.16 on 2026-08-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=50, unique=True)),
                ('confidence', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('ACKNOWLEDGED', 'Acknowledged'), ('CREW_ASSIGNED', 'Crew Assigned'), ('RESOLVED', 'Resolved'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed')], default='DETECTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_end', to='network.pole')),
                ('start_pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_start', to='network.pole')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='incidents.incident')),
            ],
        ),
    ]
