# Generated by Django 5.2.16 on 2026-08-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('DETECTED', 'Detected'), ('ACKNOWLEDGED', 'Acknowledged'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='DETECTED', max_length=20),
        ),
    ]
