# Generated by Django 5.2.16 on 2026-08-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='sequence_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
