# Generated by Django 5.2.16 on 2026-08-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetry',
            name='status',
        ),
        migrations.AddField(
            model_name='telemetry',
            name='battery_mv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='energized',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemetry',
            name='event',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemetry',
            name='firmware',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='rssi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='sequence_number',
            field=models.IntegerField(default=0),
        ),
    ]
